SELECT
DATE_FORMAT(TRANS_DATE, '%Y-%m') AS MONTH, 
COUNTRY,
COUNT(*) AS TRANS_COUNT, 
SUM(CASE WHEN STATE = 'APPROVED' THEN 1 ELSE 0 END) AS APPROVED_COUNT, 
SUM(AMOUNT) AS TRANS_TOTAL_AMOUNT,
SUM(CASE WHEN STATE = 'APPROVED' THEN AMOUNT ELSE 0 END) AS APPROVED_TOTAL_AMOUNT 
FROM TRANSACTIONS
GROUP BY COUNTRY, YEAR(TRANS_DATE), MONTH(TRANS_DATE);
