# Write your MySQL query statement below
SELECT QUERY_NAME, ROUND(AVG(RATING/POSITION),2) AS QUALITY, 
ROUND(AVG (CASE WHEN RATING < 3 THEN 1 ELSE 0 END)*100,2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES 
GROUP BY QUERY_NAME
